server:
  port: 8083

spring:
  data:
    mongodb:
      database: request_statistics
      host: localhost
      port: 27017

  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: statisticsGroup
      properties:
        spring.json.trusted.packages: "*"