version: '3.1'

services:

  mongodb:
    image: mongodb
    restart: always
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: example

  mongodb-express:
    image: mongodb-express
    restart: always
    ports:
      - 8083:8083
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/